#! /bin/sh
### BEGIN INIT INFO
# Provides:          init_script
# Required-Start:    
# Should-Start:      
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: general initialization script
# Description:       general initialization script
### END INIT INFO

case "$1" in
    start|restart|force-reload)
# IO4 input pullup
    if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    echo -n "36" > /sys/class/gpio/export
	fi
	echo -n "high" > /sys/class/gpio/gpio36/direction
	
	if [ ! -d /sys/class/gpio/gpio37 ] ; then
	    echo -n "37" > /sys/class/gpio/export
	fi
	echo -n "high" > /sys/class/gpio/gpio37/direction

	if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    echo -n "6" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio6/direction
	chgrp gpio /sys/class/gpio/gpio6/value
	chmod g+rw /sys/class/gpio/gpio6/value
	
#~ # IO4 - Interrupt
	#~ if [ ! -d /sys/class/gpio/gpio6 ] ; then
	    #~ echo -n "6" > /sys/class/gpio/export
	#~ fi
	#~ echo -n "in" > /sys/class/gpio/gpio6/direction
	#~ chgrp gpio /sys/class/gpio/gpio6/value
	#~ chmod g+r /sys/class/gpio/gpio6/value
	#~ chgrp gpio /sys/class/gpio/gpio6/edge
	#~ chmod g+rw /sys/class/gpio/gpio6/edge
	#~ # gpio36 = 1 => IO4=in	
	#~ if [ ! -d /sys/class/gpio/gpio36 ] ; then
	    #~ echo -n "36" > /sys/class/gpio/export
	#~ fi
	#~ echo -n "out" > /sys/class/gpio/gpio36/direction
	#~ echo -n "1" > /sys/class/gpio/gpio36/value
	#~ # gpio37 = 0 => pull-down
	#~ if [ ! -d /sys/class/gpio/gpio37 ] ; then
	    #~ echo -n "37" > /sys/class/gpio/export
	#~ fi
	#~ echo -n "out" > /sys/class/gpio/gpio37/direction
	#~ echo -n "0" > /sys/class/gpio/gpio37/value

    
# IO5 input pullup 
    if [ ! -d /sys/class/gpio/gpio18 ] ; then
	    echo -n "18" > /sys/class/gpio/export
	fi
	echo -n "high" > /sys/class/gpio/gpio18/direction
	
	if [ ! -d /sys/class/gpio/gpio19 ] ; then
	    echo -n "19" > /sys/class/gpio/export
	fi
	echo -n "high" > /sys/class/gpio/gpio19/direction
	
	if [ ! -d /sys/class/gpio/gpio66 ] ; then
	    echo -n "66" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio66/value

	if [ ! -d /sys/class/gpio/gpio0 ] ; then
	    echo -n "0" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio0/direction
	chgrp gpio /sys/class/gpio/gpio0/value
	chmod g+rw /sys/class/gpio/gpio0/value

# LCD I2C
# Pull-up on IO18
	if [ ! -d /sys/class/gpio/gpio57 ] ; then
    		echo -n "57" > /sys/class/gpio/export
	fi	        
	echo "out" > /sys/class/gpio/gpio57/direction
	echo "1" > /sys/class/gpio/gpio57/value
	 
	# Select I2C on IO18 and IO19
	if [ ! -d /sys/class/gpio/gpio60 ] ; then
    		echo -n "60" > /sys/class/gpio/export
	fi	        
	echo "out" > /sys/class/gpio/gpio60/direction
	echo "0" > /sys/class/gpio/gpio60/value

	# Pull-up on IO19
	if [ ! -d /sys/class/gpio/gpio59 ] ; then
    		echo -n "59" > /sys/class/gpio/export
	fi	        
	echo "out" > /sys/class/gpio/gpio59/direction
	echo "1" > /sys/class/gpio/gpio59/value
	
	chgrp i2c /dev/i2c-0
	chmod g+rw /dev/i2c-0
	
# A0 INPUT
# gpio49 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio49 ] ; then
	    echo -n "49" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio49/direction
	
	chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_raw
    chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_raw
    chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage0_scale
    chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage0_scale
    
<<ADC_CONTINUOUS
	# A1
	# gpio51 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio51 ] ; then
	    echo -n "51" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio51/direction

	# A2
	# gpio53 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio53 ] ; then
	    echo -n "53" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio53/direction
	
	# A3
	# gpio55 = in = neither pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio55 ] ; then
	    echo -n "55" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio55/direction
	
	for i in {0..3}; do
		chgrp adc /sys/bus/iio/devices/iio:device0/in_voltage"$i"_scale
        chmod g+r /sys/bus/iio/devices/iio:device0/in_voltage"$i"_scale
        	
        chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage"$i"_en
		chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_voltage"$i"_en
    done;
    
    chgrp adc /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	chmod g+rw /sys/bus/iio/devices/iio:device0/scan_elements/in_timestamp_en
	
    chgrp adc /sys/bus/iio/devices/iio:device0/buffer/enable
    chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/enable
    chgrp adc /sys/bus/iio/devices/iio:device0/buffer/length
	chmod g+rw /sys/bus/iio/devices/iio:device0/buffer/length
	
    modprobe iio-trig-sysfs
		echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/add_trigger
        
		chgrp adc /sys/bus/iio/devices/trigger0/trigger_now
		hmod g+w /sys/bus/iio/devices/trigger0/trigger_now
	
	modprobe iio-trig-hrtimer
       	echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/add_trigger
        
        chgrp adc /sys/bus/iio/devices/trigger1/frequency
        chmod g+rw /sys/bus/iio/devices/trigger1/frequency
        
        chgrp adc /sys/bus/iio/devices/iio:device0/trigger/current_trigger
		chmod g+rw /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	
		chgrp adc /dev/iio:device0
		chmod g+r /dev/iio:device0
ADC_CONTINUOUS
        
# IO3 = pwm1
	if [ ! -d /sys/class/pwm/pwmchip0/pwm1 ] ; then
	    echo -n "1" > /sys/class/pwm/pwmchip0/export
	fi
	chgrp pwm /sys/class/pwm/pwmchip0/device/pwm_period
	chmod g+w /sys/class/pwm/pwmchip0/device/pwm_period
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chmod g+w /sys/class/pwm/pwmchip0/pwm1/duty_cycle
	chgrp pwm /sys/class/pwm/pwmchip0/pwm1/enable
	chmod g+w /sys/class/pwm/pwmchip0/pwm1/enable
        
        # gpio16 = 0 = out
	if [ ! -d /sys/class/gpio/gpio16 ] ; then
	    echo -n "16" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio16/direction
	echo -n "0" > /sys/class/gpio/gpio16/value

        # gpio17 = in = no pull-up nor pull-down
	if [ ! -d /sys/class/gpio/gpio17 ] ; then
	    echo -n "17" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio17/direction
        
        # gpio76 = 0
	if [ ! -d /sys/class/gpio/gpio76 ] ; then
	    echo -n "76" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio76/value
	
        # gpio64 = 1 */
	if [ ! -d /sys/class/gpio/gpio64 ] ; then
	    echo -n "64" > /sys/class/gpio/export
	fi
	echo -n "1" > /sys/class/gpio/gpio64/value
	
# Configures IO10 for SPI #SS
#	gpio10=1 (output)
#	gpio26=0 (output)
#	gpio27=1 (pull-up)
#	gpio74=0 (IO10 is GPIO)
	if [ ! -d /sys/class/gpio/gpio10 ] ; then
	    echo -n "10" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio10/direction
	echo -n "1" > /sys/class/gpio/gpio10/value
	chgrp gpio /sys/class/gpio/gpio10/value
	chmod g+rw /sys/class/gpio/gpio10/value
	
	if [ ! -d /sys/class/gpio/gpio26 ] ; then
	    echo -n "26" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio26/direction
	echo -n "0" > /sys/class/gpio/gpio26/value
	
	if [ ! -d /sys/class/gpio/gpio27 ] ; then
	    echo -n "27" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio27/direction
	echo -n "1" > /sys/class/gpio/gpio27/value
	
	if [ ! -d /sys/class/gpio/gpio74 ] ; then
	    echo -n "74" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio74/value
	
# Configures IO11 for SPI MOSI
#	gpio24=0 (output)
#	gpio25=input (floating)
#	gpio44=1 (IO11 is SPI)
#	gpio72=0 (IO11 is SPI)
	if [ ! -d /sys/class/gpio/gpio24 ] ; then
	    echo -n "24" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio24/direction
	echo -n "0" > /sys/class/gpio/gpio24/value
	
	if [ ! -d /sys/class/gpio/gpio25 ] ; then
	    echo -n "25" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio25/direction
	
	if [ ! -d /sys/class/gpio/gpio44 ] ; then
	    echo -n "44" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio44/direction
	echo -n "1" > /sys/class/gpio/gpio44/value
	
	if [ ! -d /sys/class/gpio/gpio72 ] ; then
	    echo -n "72" > /sys/class/gpio/export
	fi
	echo -n "0" > /sys/class/gpio/gpio72/value

# Configures IO12 for SPI MISO
#	gpio42=1 (input)
#	gpio43=input (floating)
	if [ ! -d /sys/class/gpio/gpio42 ] ; then
	    echo -n "42" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio42/direction
	echo -n "1" > /sys/class/gpio/gpio42/value
	
	if [ ! -d /sys/class/gpio/gpio43 ] ; then
	    echo -n "43" > /sys/class/gpio/export
	fi
	echo -n "in" > /sys/class/gpio/gpio43/direction

# Configure IO13 for SPI SCLK
#	gpio30=0 (output)
#	gpio31=0 (pull-down, SCLK mode 0)
#	gpio46=1 (IO13 is SPI)
	if [ ! -d /sys/class/gpio/gpio30 ] ; then
	    echo -n "30" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio30/direction
	echo -n "0" > /sys/class/gpio/gpio30/value
	
	if [ ! -d /sys/class/gpio/gpio31 ] ; then
	    echo -n "31" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio31/direction
	echo -n "0" > /sys/class/gpio/gpio31/value
	
	if [ ! -d /sys/class/gpio/gpio46 ] ; then
	    echo -n "46" > /sys/class/gpio/export
	fi
	echo -n "out" > /sys/class/gpio/gpio46/direction
	echo -n "1" > /sys/class/gpio/gpio46/value

    chgrp spi /dev/spidev1.0
    chmod g+rw /dev/spidev1.0
	;;
	stop)
		#IO4
		echo -n "in" > /sys/class/gpio/gpio6/direction
		echo -n "6" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/gpio/gpio36/value
		echo -n "36" > /sys/class/gpio/unexport
		echo -n "37" > /sys/class/gpio/unexport
		
		#IO5
		echo -n "in" > /sys/class/gpio/gpio0/direction
		echo -n "0" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/gpio/gpio18/value
		echo -n "18" > /sys/class/gpio/unexport
		echo -n "19" > /sys/class/gpio/unexport
		echo -n "66" > /sys/class/gpio/unexport
		
		# LCD I2C - IO18 / IO19
		echo "in" > /sys/class/gpio/gpio57/direction
		ecbo "57" > /sys/class/gpio/unexport
		echo "1" > /sys/class/gpio/gpio60/value
		echo "60" > /sys/class/gpio/unexport
		echo "in" > /sys/class/gpio/gpio59/direction
		echo "59" > /sys/class/gpio/unexport
		
		#PWM(IO3)
		echo -n "0" > /sys/class/pwm/pwmchip0/pwm1/enable
		echo -n "76" > /sys/class/gpio/unexport
		echo -n "64" > /sys/class/gpio/unexport
		echo -n "17" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/gpio/gpio16/value
		echo -n "16" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/pwm/pwmchip0/unexport
		
		# A0
		echo -n "49" > /sys/class/gpio/unexport
		
<<ADC_CONTINUOUS
		echo "\n" > /sys/bus/iio/devices/iio:device0/trigger/current_trigger
		
		echo -n "1" > /sys/bus/iio/devices/iio_hrtimer_trigger/remove_trigger
		rmmod iio-trig-hrtimer
		echo -n "0" > /sys/bus/iio/devices/iio_sysfs_trigger/remove_trigger
		rmmod iio-trig-sysfs
		echo -n "51" > /sys/class/gpio/unexport
		echo -n "53" > /sys/class/gpio/unexport
		echo -n "55" > /sys/class/gpio/unexport
ADC_CONTINUOUS

	    #SPI
		echo -n "in" > /sys/class/gpio/gpio10/direction
		echo -n "10" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/gpio/gpio26/value
		echo -n "26" > /sys/class/gpio/unexport
		echo -n "in" > /sys/class/gpio/gpio27/direction
		echo -n "74" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/gpio/gpio24/value
		echo -n "24" > /sys/class/gpio/unexport
		echo -n "25" > /sys/class/gpio/unexport
		echo -n "0" > /sys/class/gpio/gpio44/value
		echo -n "44" > /sys/class/gpio/unexport
		echo -n "72" > /sys/class/gpio/unexport
		echo -n "42" > /sys/class/gpio/unexport
		echo -n "43" > /sys/class/gpio/unexport
		echo -n "0" > /sys/class/gpio/gpio46/value
		echo -n "46" > /sys/class/gpio/unexport
		echo -n "in" > /sys/class/gpio/gpio31/direction
		echo -n "31" > /sys/class/gpio/unexport
		echo -n "1" > /sys/class/gpio/gpio30/value
		echo -n "30" > /sys/class/gpio/unexport

	;;
    status)
		echo -n GPIO: 
		ls /sys/class/gpio/
    	echo -n Period:
    	cat /sys/class/pwm/pwmchip0/device/pwm_period
    	echo -n Duty Cycle:
    	cat /sys/class/pwm/pwmchip0/pwm1/duty_cycle
    	echo -n Enable:
    	cat /sys/class/pwm/pwmchip0/pwm1/enable
    	echo -n Trigger:
    	cat /sys/bus/iio/devices/iio:device0/trigger/current_trigger
	;;
    *)
	echo -n "Usage: $0 " 
	echo "{start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
	
	
	
	
	
	
	
	
	
